# Generated by Django 4.0.4 on 2023-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0020_alter_jmp_materialized_view'),
        ('v1_profile', '0006_alter_access_role'),
        ('v1_mobile', '0003_mobileapk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileassignment',
            name='administrations',
            field=models.ManyToManyField(to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='forms',
            field=models.ManyToManyField(to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
