# Generated by Django 4.0.4 on 2023-11-30 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0021_alter_formapprovalassignment_administration_and_more'),
        ('v1_profile', '0011_remove_administrationattributevalue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_mobile', '0003_mobileapk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileassignment',
            name='administrations',
            field=models.ManyToManyField(to='v1_profile.administration'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='forms',
            field=models.ManyToManyField(to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobileassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
