# Generated by Django 4.0.4 on 2024-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_mobile', '0004_mobileassignment_administrations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileassignment',
            name='last_synced_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
