# Generated by Django 4.0.4 on 2024-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0015_alter_entitydata_administration_and_more'),
        ('v1_mobile', '0005_mobileassignment_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileassignment',
            name='certifications',
            field=models.ManyToManyField(related_name='certifications', to='v1_profile.administration'),
        ),
    ]
