# Generated by Django 4.0.1 on 2022-01-28 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('code',
                 models.CharField(default=None, max_length=255, null=True)),
                ('name', models.TextField()),
                ('level',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='administrator_level',
                                   to='v1_profile.levels')),
                ('parent', models.ForeignKey(default=None, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='parent_administration',
                                             to='v1_profile.administration')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('role', models.IntegerField(
                    choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Approver'),
                             (4, 'User')])),
                ('administration',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user_administration',
                                   to='v1_profile.administration')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user_access',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access',
            },
        ),
    ]
