# Generated by Django 4.0.1 on 2022-01-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
