# Generated by Django 4.0.1 on 2022-02-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0002_alter_access_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='path',
            field=models.TextField(default=None, null=True),
            preserve_default=False,
        ),
    ]
