# Generated by Django 4.0.4 on 2022-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0005_alter_access_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super Admin'),
                                               (2, 'County Admin'),
                                               (3, 'Data Approver'),
                                               (4, 'Data Entry Staff'),
                                               (5, 'Institutional User')]),
        ),
    ]
