# Generated by Django 4.0.4 on 2023-11-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0007_administrationattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='v1_profile.administration')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_profile.administrationattribute')),
            ],
            options={
                'db_table': 'administration_attribute_value',
            },
        ),
    ]
