# Generated by Django 4.0.4 on 2023-11-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0008_administrationattributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_administration', to='v1_profile.administration'),
        ),
    ]
