# Generated by Django 4.0.4 on 2023-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0010_administrationattribute_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrationattributevalue',
            name='options',
        ),
        migrations.AlterField(
            model_name='administrationattributevalue',
            name='value',
            field=models.JSONField(default=dict),
        ),
    ]
