# Generated by Django 4.0.4 on 2023-12-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0011_remove_administrationattributevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='EntityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.CharField(default=None, max_length=255, null=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='v1_profile.administration')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='v1_profile.entity')),
            ],
            options={
                'db_table': 'entity_data',
            },
        ),
    ]
