# Generated by Django 4.0.4 on 2024-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0013_alter_access_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='role',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'County Admin'), (3, 'Data Approver'), (4, 'Data Entry Supervisor')]),
        ),
    ]
