# Generated by Django 4.0.4 on 2024-02-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0014_alter_access_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydata',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_data', to='v1_profile.administration'),
        ),
        migrations.AlterField(
            model_name='entitydata',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_data', to='v1_profile.entity'),
        ),
    ]
