# Generated by Django 4.0.1 on 2022-02-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='question_question_options',
                to='v1_forms.questions'),
        ),
    ]
