# Generated by Django 4.0.1 on 2022-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_forms', '0003_alter_formdata_name_alter_pendingformdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
