# Generated by Django 4.0.1 on 2022-02-04 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_forms', '0004_alter_answers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerhistory',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formapprovalassignment',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='form_data_updated',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendinganswers',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
