# Generated by Django 4.0.1 on 2022-02-11 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('v1_forms',
         '0005_alter_answerhistory_updated_alter_answers_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='data',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pendinganswers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pendinganswers',
            name='pending_data',
        ),
        migrations.RemoveField(
            model_name='pendinganswers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pendingdataapproval',
            name='pending_data',
        ),
        migrations.RemoveField(
            model_name='pendingdataapproval',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='administration',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pendingformdata',
            name='form',
        ),
        migrations.DeleteModel(
            name='AnswerHistory',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
        migrations.DeleteModel(
            name='PendingAnswers',
        ),
        migrations.DeleteModel(
            name='PendingDataApproval',
        ),
        migrations.DeleteModel(
            name='PendingFormData',
        ),
    ]
