# Generated by Django 4.0.2 on 2022-04-14 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_forms', '0007_alter_questions_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_user', to='v1_forms.forms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_form',
            },
        ),
    ]
