# Generated by Django 4.0.4 on 2022-07-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0008_userforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttribute',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.TextField()),
                ('attribute',
                 models.IntegerField(
                     choices=[
                         (1, 'chart'),
                         (2, 'aggregate'),
                         (3, 'table'),
                         (4, 'jmp')])),
                ('options', models.JSONField(default=None, null=True)),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='question_question_attribute',
                                   to='v1_forms.questions')),
            ],
            options={
                'db_table': 'question_attribute',
                'unique_together': {('question', 'attribute', 'options')},
            },
        ),
    ]
