# Generated by Django 4.0.4 on 2022-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0010_alter_userforms_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattribute',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
