# Generated by Django 4.0.4 on 2022-07-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0011_alter_questionattribute_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionattribute',
            unique_together={('name', 'question', 'attribute', 'options')},
        ),
    ]
