# Generated by Django 4.0.4 on 2022-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0012_alter_questionattribute_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewJmpCriteria',
            fields=[
                ('id', models.BigIntegerField(
                    primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_jmp_criteria',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW view_jmp_criteria as
                SELECT ROW_NUMBER() OVER (PARTITION BY TRUE) AS id,
                    qa.form_id,
                    Split_part(qa.name, '|', 1) AS name,
                    Split_part(qa.name, '|', 2) AS level,
                    Jsonb_agg(qa.option)        AS criteria
                FROM   (SELECT q.name,
                            qs.form_id,
                            Concat(q.question_id, '||', Lower(
                            Jsonb_array_elements_text(q.options)))
                                    AS
                            option
                        FROM   question_attribute q
                            left join question qs
                                    ON q.question_id = qs.id
                        WHERE  q.attribute = 4) qa
                GROUP  BY qa.form_id,
                        qa.name
                ORDER  BY qa.name;
            """,
            """
            DROP MATERIALIZED VIEW view_jmp_criteria;
            """
        )
    ]
