# Generated by Django 4.0.4 on 2022-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
            ('v1_forms', '0013_materialized_viewjmpcriteria'),
            ('v1_data', '0019_materialized_viewdataoptions')]

    operations = [
        migrations.CreateModel(
            name='ViewJmpData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True,
                                              serialize=False)),
            ],
            options={
                'db_table': 'view_jmp_data',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW view_jmp_data as
            SELECT row_number() OVER (PARTITION BY true::boolean) AS id,
                    d.data_id,
                    a.path,
                    d.form_id,
                    c.name,
                    c.level,
                    COUNT(*) as matches
            FROM view_data_options D
            LEFT JOIN view_jmp_criteria C
                ON c.form_id = d.form_id
            LEFT join data dt
                ON dt.id = d.data_id
            LEFT JOIN administrator A
                ON dt.administration_id = a.id
            WHERE d.options ?|
                TRANSLATE(c.criteria::jsonb::text,'[]','{}')::text[]
            GROUP BY
                d.data_id, a.path, d.form_id,
                c.name, c.level
            ORDER BY d.data_id,
                d.form_id, c.name, c.level;
        """, """
            DROP MATERIALIZED VIEW view_jmp_data;
        """)
    ]
