# Generated by Django 4.0.4 on 2022-07-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0015_refresh_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattribute',
            name='attribute',
            field=models.IntegerField(choices=[
                (1, 'chart'),
                (2, 'aggregate'),
                (3, 'table'),
                (4, 'jmp'),
                (5, 'advanced_filter')]),
        ),
    ]
