# Generated by Django 4.0.4 on 2022-07-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0016_alter_questionattribute_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='api',
            field=models.JSONField(default=None, null=True),
        ),
    ]
