# Generated by Django 4.0.4 on 2022-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0017_questions_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='extra',
            field=models.JSONField(default=None, null=True),
        ),
    ]
