# Generated by Django 4.0.4 on 2022-08-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0018_questions_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='order',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
