# Generated by Django 4.0.4 on 2022-08-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0019_questiongroup_order'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW view_jmp_count;
            DROP MATERIALIZED VIEW view_jmp_data;
            DROP MATERIALIZED VIEW view_jmp_criteria;
            CREATE MATERIALIZED VIEW view_jmp_criteria as
                SELECT row_number() OVER (PARTITION BY true::boolean) AS id,
                    qa.form_id,
                    split_part(qa.name, '|'::text, 1) AS name,
                    split_part(qa.name, '|'::text, 2) AS level,
                    split_part(qa.name, '|'::text, 4)::text AS group_name,
                    split_part(qa.name, '|'::text, 3)::int AS score,
                    jsonb_agg(qa.option) AS criteria
                 FROM (
                     SELECT
                         q.name,
                         qs.form_id,
                         q.question_id,
                         concat(q.question_id, '||', lower(
                         jsonb_array_elements_text(q.options))) AS
                         option
                      FROM question_attribute q
                      LEFT JOIN question qs ON q.question_id = qs.id
                      WHERE q.attribute = 4) qa
                GROUP BY qa.form_id, qa.name
                ORDER BY qa.name;

            CREATE MATERIALIZED VIEW view_jmp_data as
            SELECT row_number() OVER (PARTITION BY true::boolean) AS id,
                    d.data_id,
                    a.path,
                    d.form_id,
                    c.name,
                    c.level,
                    c.score::int,
                    COUNT(*) as matches
            FROM view_data_options D
            LEFT JOIN view_jmp_criteria C
                ON c.form_id = d.form_id
            LEFT join data dt
                ON dt.id = d.data_id
            LEFT JOIN administrator A
                ON dt.administration_id = a.id
            WHERE d.options ?|
                TRANSLATE(c.criteria::jsonb::text,'[]','{}')::text[]
            GROUP BY
                d.data_id, a.path, d.form_id,
                c.name, c.level, c.score
            ORDER BY d.data_id,
                d.form_id, c.name, c.level;

            CREATE MATERIALIZED VIEW view_jmp_count as
            SELECT ROW_NUMBER() OVER (PARTITION BY TRUE) AS id,
                d.form_id,
                d.path,
                d.name,
                d.level,
                count(data_id) as total
            FROM view_jmp_data d
            LEFT JOIN
            (
                SELECT vjc.form_id, vjc.name, vjc.level, count(vjc.id)
                FROM view_jmp_criteria vjc
                GROUP BY vjc.form_id, vjc.name, vjc.level
            ) c
            ON
                c.form_id = d.form_id
                AND c.name = d.name
                AND c.level = d.level
            WHERE
                d.matches = c.count
            GROUP BY
                d.form_id, d.name, d.path, d.level, d.matches
            ORDER BY
                d.form_id, d.name DESC;
            """,
            """
            DROP MATERIALIZED VIEW view_jmp_count;
            DROP MATERIALIZED VIEW view_jmp_data;
            DROP MATERIALIZED VIEW view_jmp_criteria;
            CREATE MATERIALIZED VIEW view_jmp_criteria as
                SELECT row_number() OVER (PARTITION BY true::boolean) AS id,
                    qa.form_id,
                    split_part(qa.name, '|'::text, 1) AS name,
                    split_part(qa.name, '|'::text, 2) AS level,
                    split_part(qa.name, '|'::text, 3)::int AS score,
                    jsonb_agg(qa.option) AS criteria
                 FROM (
                     SELECT
                         q.name,
                         qs.form_id,
                         q.question_id,
                         concat(q.question_id, '||', lower(
                         jsonb_array_elements_text(q.options))) AS
                         option
                      FROM question_attribute q
                      LEFT JOIN question qs ON q.question_id = qs.id
                      WHERE q.attribute = 4) qa
                GROUP BY qa.form_id, qa.name, qa.question_id
                ORDER BY qa.name;

            CREATE MATERIALIZED VIEW view_jmp_data as
            SELECT row_number() OVER (PARTITION BY true::boolean) AS id,
                    d.data_id,
                    a.path,
                    d.form_id,
                    c.name,
                    c.level,
                    c.score::int,
                    COUNT(*) as matches
            FROM view_data_options D
            LEFT JOIN view_jmp_criteria C
                ON c.form_id = d.form_id
            LEFT join data dt
                ON dt.id = d.data_id
            LEFT JOIN administrator A
                ON dt.administration_id = a.id
            WHERE d.options ?|
                TRANSLATE(c.criteria::jsonb::text,'[]','{}')::text[]
            GROUP BY
                d.data_id, a.path, d.form_id,
                c.name, c.level, c.score
            ORDER BY d.data_id,
                d.form_id, c.name, c.level;

            CREATE MATERIALIZED VIEW view_jmp_count as
            SELECT ROW_NUMBER() OVER (PARTITION BY TRUE) AS id,
                d.form_id,
                d.path,
                d.name,
                d.level,
                count(data_id) as total
            FROM view_jmp_data d
            LEFT JOIN
            (
                SELECT vjc.form_id, vjc.name, vjc.level, count(vjc.id)
                FROM view_jmp_criteria vjc
                GROUP BY vjc.form_id, vjc.name, vjc.level
            ) c
            ON
                c.form_id = d.form_id
                AND c.name = d.name
                AND c.level = d.level
            WHERE
                d.matches = c.count
            GROUP BY
                d.form_id, d.name, d.path, d.level, d.matches
            ORDER BY
                d.form_id, d.name DESC;
            """
        )
    ]
