# Generated by Django 4.0.4 on 2023-11-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0009_alter_administration_parent'),
        ('v1_forms', '0020_alter_jmp_materialized_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapprovalassignment',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_data_approval', to='v1_profile.administration'),
        ),
        migrations.AlterField(
            model_name='formapprovalrule',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_form_approval', to='v1_profile.administration'),
        ),
    ]
