# Generated by Django 4.0.4 on 2023-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0021_alter_formapprovalassignment_administration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='approval_instructions',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='color',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='fn',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='tooltip',
            field=models.JSONField(default=None, null=True),
        ),
    ]
