# Generated by Django 4.0.4 on 2023-12-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0022_forms_approval_instructions_questionoptions_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='hidden',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='pre',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.IntegerField(choices=[(1, 'Geo'), (2, 'Administration'), (3, 'Text'), (4, 'Number'), (5, 'Option'), (6, 'Multiple_Option'), (7, 'Cascade'), (8, 'Photo'), (9, 'Date'), (10, 'Autofield')]),
        ),
    ]
