# Generated by Django 4.0.4 on 2024-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0024_questions_display_only_questions_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='meta_uuid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
