# Generated by Django 4.0.4 on 2024-02-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0026_delete_formapprovalrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='variable',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('form', 'variable')},
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('form', 'variable'), name='unique_form_variable'),
        ),
    ]
