# Generated by Django 4.0.4 on 2024-02-21 03:35

from django.db import migrations, models

def replace_name_with_variable(apps, schema_editor):
    Questions = apps.get_model('v1_forms', 'Questions')
    for instance in Questions.objects.all():
        instance.name = instance.variable
        instance.save()

def rollback_variable_with_name(apps, schema_editor):
    Questions = apps.get_model('v1_forms', 'Questions')
    for instance in Questions.objects.all():
        instance.variable = instance.name
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0027_questions_variable_alter_questions_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(
            replace_name_with_variable,
            reverse_code=rollback_variable_with_name
        ),
        migrations.RemoveConstraint(
            model_name='questions',
            name='unique_form_variable',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='text',
            new_name='label',
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('form', 'name')},
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('form', 'name'), name='unique_form_question'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='variable',
        ),
    ]
