# Generated by Django 4.0.4 on 2024-02-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0028_remove_questions_unique_form_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='label',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('form', 'name')},
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('form', 'name'), name='unique_form_question_group'),
        ),
    ]
