# Generated by Django 4.0.4 on 2024-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0029_questiongroup_label_alter_questiongroup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='short_label',
            field=models.TextField(default=None, null=True),
        ),
    ]
