# Generated by Django 4.0.4 on 2024-02-21 08:45

import re
from django.db import migrations, models
import django.db.models.deletion
from django.db import connection

def clean_string(input_string):
    stripped_string = input_string.strip()
    lowercase_string = stripped_string.lower()
    no_special_chars_string = re.sub(r'[^a-z0-9 ]', '', lowercase_string)
    underscore_string = no_special_chars_string.replace(' ', '_')
    final_string = underscore_string.strip('_')
    return final_string

def remove_duplicate_options(apps, schema_editor):
    Options = apps.get_model('v1_forms', 'QuestionOptions')
    Question = apps.get_model('v1_forms', 'Questions')
    for question in Question.objects.all():
        options = Options.objects.filter(question=question).order_by('id')
        for option in options[1:]:
            option.delete()


def add_label_value(apps, schema_editor):
    Options = apps.get_model('v1_forms', 'QuestionOptions')
    for instance in Options.objects.all():
        instance.label = instance.name
        instance.value = clean_string(instance.name)
        instance.save()

def rollback_label_value(apps, schema_editor):
    Options = apps.get_model('v1_forms', 'QuestionOptions')
    for instance in Options.objects.all():
        instance.name = instance.label
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0030_questions_short_label'),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_options,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RenameField(
            model_name='questionoptions',
            old_name='code',
            new_name='value',
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='label',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='v1_forms.questions'),
        ),
        migrations.AlterUniqueTogether(
            name='questionoptions',
            unique_together={('question', 'value')},
        ),
        migrations.AddConstraint(
            model_name='questionoptions',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_question_option'),
        ),
        migrations.RunPython(
            add_label_value,
            reverse_code=rollback_label_value,
        ),
    ]
