# Generated by Django 4.0.4 on 2024-03-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0032_remove_questionoptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='default_value',
            field=models.JSONField(default=None, null=True),
        ),
    ]
