# Generated by Django 4.0.4 on 2024-03-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0033_questions_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='monitoring',
        ),
    ]
