# Generated by Django 4.0.4 on 2024-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0034_remove_questions_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='disabled',
            field=models.JSONField(default=None, null=True),
        ),
    ]
