# Generated by Django 4.0.4 on 2024-03-27 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0035_questions_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='submission_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring'), (3, 'Verification'), (4, 'Certification')]), blank=True, default=list, size=None),
        ),
    ]
