# Generated by Django 4.0.4 on 2024-04-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1_forms", "0037_formcertificationadministration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="hidden",
        ),
        migrations.AddField(
            model_name="questions",
            name="hidden",
            field=models.JSONField(default=None, null=True),
        ),
    ]
