# Generated by Django 4.0.1 on 2022-01-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
