# Generated by Django 4.0.1 on 2022-03-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_users', '0002_systemuser_first_name_systemuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='designation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
