# Generated by Django 4.0.1 on 2022-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_users', '0003_systemuser_designation_systemuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
