# Generated by Django 4.0.4 on 2022-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0004_systemuser_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
