# Generated by Django 4.0.4 on 2024-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0008_reset_organisation_id_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
