# Generated by Django 4.0.1 on 2022-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingformdata',
            name='batch',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
