# Generated by Django 4.0.1 on 2022-02-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_profile', '0004_alter_administration_path'),
        ('v1_data', '0002_pendingformdata_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdataapproval',
            name='level',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='level_assigned_pending_data',
                                    to='v1_profile.levels'),
            preserve_default=False,
        ),
    ]
