# Generated by Django 4.0.1 on 2022-02-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_data', '0003_pendingdataapproval_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinganswers',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
