# Generated by Django 4.0.1 on 2022-03-02 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_forms', '0007_alter_questions_type'),
        ('v1_profile', '0004_alter_administration_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_data', '0004_alter_pendinganswers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingformdata',
            name='batch',
        ),
        migrations.CreateModel(
            name='PendingDataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.TextField()),
                ('uuid', models.UUIDField(default=None, null=True)),
                ('file', models.URLField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('administration',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='administration_pending_data_batch',
                                   to='v1_profile.administration')),
                ('form',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='form_batch_data',
                                   to='v1_forms.forms')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user_pending_data_batch',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch',
            },
        ),
    ]
