# Generated by Django 4.0.1 on 2022-03-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_data', '0005_remove_pendingformdata_batch_pendingdatabatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingformdata',
            name='batch',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='v1_data.pendingdatabatch'),
        ),
    ]
