# Generated by Django 4.0.1 on 2022-03-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_data', '0006_pendingformdata_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingformdata',
            name='batch',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='batch_pending_data_batch',
                                    to='v1_data.pendingdatabatch'),
        ),
    ]
