# Generated by Django 4.0.1 on 2022-03-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0007_alter_pendingformdata_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdataapproval',
            name='pending_data',
        ),
        migrations.AddField(
            model_name='pendingdataapproval',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batch_approval', to='v1_data.pendingdatabatch'),
            preserve_default=False,
        ),
    ]
