# Generated by Django 4.0.1 on 2022-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0008_remove_pendingdataapproval_pending_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingformdata',
            name='approved',
        ),
        migrations.AddField(
            model_name='pendingdatabatch',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
