# Generated by Django 4.0.2 on 2022-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_data', '0009_remove_pendingformdata_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPendingDataApproval',
            fields=[
                ('id',
                 models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(
                    choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')],
                    default=1)),
                ('pending_level', models.IntegerField()),
            ],
            options={
                'db_table': 'view_pending_approval',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """CREATE VIEW view_pending_approval as SELECT 
  DISTINCT pa.*, 
  COALESCE(
    max(pa2.level_id), 
    0
  ) as pending_level 
FROM 
  pending_data_approval pa 
  LEFT JOIN (
    SELECT 
      * 
    FROM 
      pending_data_approval pda 
    WHERE 
      pda.status = 1
  ) as pa2 ON pa2.batch_id = pa.batch_id 
GROUP BY 
  pa.id
""",
            "DROP VIEW view_pending_approval;"
        )
    ]
