# Generated by Django 4.0.2 on 2022-03-15 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_data', '0011_auto_20220315_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDataBatchComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('batch',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='batch_batch_comment',
                                   to='v1_data.pendingdatabatch')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='user_batch_comment',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_comment',
            },
        ),
    ]
