# Generated by Django 4.0.2 on 2022-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_data', '0013_alter_answerhistory_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerhistory',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
