# Generated by Django 4.0.4 on 2022-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0014_alter_answerhistory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDataOptions',
            fields=[
                ('id', models.BigIntegerField(
                    primary_key=True, serialize=False)),
                ('options', models.JSONField(default=None, null=True)),
            ],
            options={
                'db_table': 'view_data_options',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW view_data_options as
                SELECT
                    tmp.data_id,
                    d.administration_id,
                    d.form_id,
                    to_jsonb(array_agg(
                        concat(tmp.question_id, '||',
                            lower(tmp.options::text))
                    )) as options
                FROM (
                    SELECT
                        a.data_id,
                        a.question_id,
                        a.id as answer_id,
                        jsonb_array_elements_text(a.options) as options
                    FROM answer a LEFT JOIN question q on q.id = a.question_id
                    WHERE q.type = 5  or q.type = 6
                ) tmp
                LEFT JOIN data d ON d.id = tmp.data_id
                GROUP BY tmp.data_id, d.administration_id, d.form_id
            """, "DROP VIEW view_data_options;")
    ]
