# Generated by Django 4.0.4 on 2022-05-27 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_data', '0016_pendinganswerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingformdata',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pendingformdata',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_form_data_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
