# Generated by Django 4.0.4 on 2022-05-30 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_data', '0017_pendingformdata_updated_pendingformdata_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinganswerhistory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_answer_history_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingformdata',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_form_data_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
