# Generated by Django 4.0.4 on 2022-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0019_materialized_viewdataoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewOptions',
            fields=[
                ('id', models.BigIntegerField(
                    primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_options',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW view_options as
            SELECT ROW_NUMBER() OVER (PARTITION BY TRUE) AS id,
                    a.id AS answer_id,
                    a.administration_id,
                    a.form_id,
                    a.data_id,
                    a.question_id,
                    REPLACE(o.name::text,'"', '') AS options
            FROM (
                SELECT aw.*,
                d.administration_id,
                d.form_id
                FROM answer aw
                LEFT JOIN data d ON d.id = aw.data_id) a,
                    LATERAL JSON_ARRAY_ELEMENTS(a.options::JSON) WITH
            ORDINALITY AS o(name, rid)
            WHERE a.options IS NOT NULL;
            """,
            """
            DROP MATERIALIZED VIEW view_options;
            """
        )
    ]
