# Generated by Django 4.0.4 on 2022-07-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0020_materialized_viewoptions'),
    ]

    operations = [
        migrations.RunSQL(
            # take view_options definition, drop, alter, recreate view
            """
            DO $$
                DECLARE view_options_detail_text text;
                DECLARE exec_text text;
            BEGIN
            view_options_detail_text := pg_get_viewdef('view_options');
            DROP MATERIALIZED VIEW view_options;

            -- alter value column to float
            ALTER TABLE answer_history
                ALTER COLUMN value TYPE float USING value::float;
            ALTER TABLE answer_history
                ALTER COLUMN value SET DEFAULT NULL;

            ALTER TABLE answer
                ALTER COLUMN value TYPE float USING value::float;
            ALTER TABLE answer
                ALTER COLUMN value SET DEFAULT NULL;

            ALTER TABLE pending_answer_history
                ALTER COLUMN value TYPE float USING value::float;
            ALTER TABLE pending_answer_history
                ALTER COLUMN value SET DEFAULT NULL;

            ALTER TABLE pending_answer
                ALTER COLUMN value TYPE float USING value::float;
            ALTER TABLE pending_answer
                ALTER COLUMN value SET DEFAULT NULL;
            -- end alter value column to float

            exec_text := format('CREATE MATERIALIZED VIEW view_options as %s',
                view_options_detail_text);
            EXECUTE exec_text;
            END $$;
            """,
            # rollback
            """
            DO $$
                DECLARE view_options_detail_text text;
                DECLARE exec_text text;
            BEGIN
            view_options_detail_text := pg_get_viewdef('view_options');
            DROP MATERIALIZED VIEW view_options;

            -- alter value column to bigint
            ALTER TABLE answer_history
                ALTER COLUMN value TYPE bigint USING value::bigint;
            ALTER TABLE answer_history
                ALTER COLUMN value SET DEFAULT NULL;

            ALTER TABLE answer
                ALTER COLUMN value TYPE bigint USING value::bigint;
            ALTER TABLE answer
                ALTER COLUMN value SET DEFAULT NULL;

            ALTER TABLE pending_answer_history
                ALTER COLUMN value TYPE bigint USING value::bigint;
            ALTER TABLE pending_answer_history
                ALTER COLUMN value SET DEFAULT NULL;

            ALTER TABLE pending_answer
                ALTER COLUMN value TYPE bigint USING value::bigint;
            ALTER TABLE pending_answer
                ALTER COLUMN value SET DEFAULT NULL;
            -- end alter value column to bigint

            exec_text := format('CREATE MATERIALIZED VIEW view_options as %s',
                view_options_detail_text);
            EXECUTE exec_text;
            END $$;
            """
        )
        # migrations.AlterField(
        #     model_name='answerhistory',
        #     name='value',
        #     field=models.FloatField(default=None, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='answers',
        #     name='value',
        #     field=models.FloatField(default=None, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='pendinganswerhistory',
        #     name='value',
        #     field=models.FloatField(default=None, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='pendinganswers',
        #     name='value',
        #     field=models.FloatField(default=None, null=True),
        # ),
    ]
