# Generated by Django 4.0.4 on 2022-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data',
         '0021_alter_answerhistory_value_alter_answers_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewJMPData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True,
                                              serialize=False)),
                ('path', models.TextField(default=None, null=True)),
                ('name', models.TextField()),
                ('level', models.TextField()),
                ('matches', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'view_jmp_data',
                'managed': False,
            },
        )
    ]
