# Generated by Django 4.0.4 on 2022-07-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0022_refresh_models'),
        ('v1_forms', '0014_materialized_viewjmpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewJMPCount',
            fields=[
                ('id', models.BigIntegerField(primary_key=True,
                                              serialize=False)),
                ('path', models.TextField(default=None, null=True)),
                ('name', models.TextField()),
                ('level', models.TextField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'view_jmp_count',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW view_jmp_count as
            SELECT ROW_NUMBER() OVER (PARTITION BY TRUE) AS id,
                d.form_id,
                d.path,
                d.name,
                d.level,
                count(data_id) as total
            FROM view_jmp_data d
            LEFT JOIN
            (
                SELECT vjc.form_id, vjc.name, vjc.level, count(vjc.id)
                FROM view_jmp_criteria vjc
                GROUP BY vjc.form_id, vjc.name, vjc.level
            ) c
            ON
                c.form_id = d.form_id
                AND c.name = d.name
                AND c.level = d.level
            WHERE
                d.matches = c.count
            GROUP BY
                d.form_id, d.name, d.path, d.level, d.matches
            ORDER BY
                d.form_id, d.name DESC;
            """, """
            DROP MATERIALIZED VIEW view_jmp_count;
            """)
    ]
