# Generated by Django 4.0.4 on 2023-11-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0023_viewjmpcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingformdata',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingformdata',
            name='submitter',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
