# Generated by Django 4.0.4 on 2023-11-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0009_alter_administration_parent'),
        ('v1_data', '0023_viewjmpcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_form_data', to='v1_profile.administration'),
        ),
        migrations.AlterField(
            model_name='pendingdatabatch',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_pending_data_batch', to='v1_profile.administration'),
        ),
        migrations.AlterField(
            model_name='pendingformdata',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administration_pending_form_data', to='v1_profile.administration'),
        ),
    ]
