# Generated by Django 4.0.4 on 2024-01-08 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0026_pendingformdata_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingformdata',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
