# Generated by Django 4.0.4 on 2024-02-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0027_formdata_uuid_pendingformdata_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingformdata',
            old_name='deleted',
            new_name='deleted_at',
        ),
    ]
