# Generated by Django 4.0.4 on 2024-02-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0028_rename_deleted_pendingformdata_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='v1_data.formdata'),
        ),
    ]
