# Generated by Django 4.0.4 on 2024-02-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0029_formdata_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='v1_data.formdata'),
        ),
    ]
