# Generated by Django 4.0.4 on 2024-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0031_alter_formdata_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='submission_type',
            field=models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring'), (3, 'Verification'), (4, 'Certification')], default=1),
        ),
        migrations.AddField(
            model_name='pendingformdata',
            name='submission_type',
            field=models.IntegerField(choices=[(1, 'Registration'), (2, 'Monitoring'), (3, 'Verification'), (4, 'Certification')], default=1),
        ),
    ]
