# Generated by Django 4.0.4 on 2024-03-27 06:58

from django.db import migrations
from api.v1.v1_forms.constants import SubmissionTypes


def add_submission_types(apps, schema_editor):
    FormData = apps.get_model('v1_data', 'FormData')
    for instance in FormData.objects.all():
        if instance.parent:
            instance.submission_type = SubmissionTypes.monitoring
        else:
            instance.submission_type = SubmissionTypes.registration
        instance.save()
    PendingFormData = apps.get_model('v1_data', 'PendingFormData')
    for instance in PendingFormData.objects.all():
        registration = FormData.objects.filter(
            uuid=instance.uuid).first()
        if registration:
            instance.submission_type = SubmissionTypes.monitoring
        else:
            instance.submission_type = SubmissionTypes.registration
        instance.save()

def rollback_submission_types(apps, schema_editor):
    FormData = apps.get_model('v1_data', 'FormData')
    for instance in FormData.objects.all():
        instance.submission_type = None

class Migration(migrations.Migration):

    dependencies = [
        ('v1_data', '0032_formdata_submission_type_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_submission_types,
            reverse_code=rollback_submission_types
        ),
    ]
