# Generated by Django 4.0.2 on 2022-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('v1_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='task_id',
            field=models.CharField(default=None, max_length=50, null=True,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID'),
        ),
    ]
