# Generated by Django 4.0.4 on 2024-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_jobs', '0003_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.IntegerField(choices=[(1, 'send_email'), (2, 'validate_data'), (3, 'seed_data'), (4, 'download'), (5, 'download_administration'), (6, 'download_entities')]),
        ),
    ]
