# Generated by Django 4.0.1 on 2022-01-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'country_master',
            },
        ),
    ]
