# Generated by Django 4.0.1 on 2022-01-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demo', '0002_city_registeredusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='administration',
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='user_city', to='demo.city'),
        ),
    ]
