# Generated by Django 4.0.4 on 2023-06-05 01:55

from django.db import migrations
from ..management.commands.generate_views import generate_schema


class Migration(migrations.Migration):
    dependencies = [
        ("v1_categories", "0001_initial"),
    ]
    file_path = "./source/config/category.json"
    operations = [
        migrations.RunSQL(
            generate_schema(file_path=file_path),
            """
            DROP MATERIALIZED VIEW data_category;
            """,
        )
    ]
