# Generated by Django 4.0.4 on 2023-06-05 01:55

from django.db import migrations
from django.core.management import call_command


def generate_category_views(apps, schema_editor):
    call_command("generate_views")


class Migration(migrations.Migration):
    dependencies = [
        ("v1_categories", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(
            generate_category_views,
            reverse_code=migrations.RunPython.noop)
    ]
